server:
  port: 8888
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kadamovnk/config-repo.git
          default-label: main
          clone-on-start: true
          username: ${CONFIG_USERNAME}
          password: ${CONFIG_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,metrics
  endpoint:
    health:
      show-details: when_authorized