server:
  port: 8001

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server:8001/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
  instance:
    hostname: eureka-server
  dashboard:
    enabled: true

# Reduce noise in logs
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,metrics
  endpoint:
    health:
      show-details: when_authorized