server:
  port: 8082

spring:
  application:
    name: processing-center
  datasource:
    url: jdbc:postgresql://localhost:5432/processing_center_db
    username: kadamovnk
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPool-ProcessingCenter
      auto-commit: true
      
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    
  cache:
    type: redis

# OpenAPI configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Processing Center specific settings
processing-center:
  transaction-timeout: 60
  batch-size: 100
