server:
  port: 8082

spring:
  application:
    name: sales-point

  datasource:
    url: jdbc:postgresql://postgres_db_sales_point:5432/sales_point_db
    username: kadamovnk
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPool-SalesPoint
      auto-commit: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  data:
    redis:
      host: redis_sales_point
      port: 6379

  cache:
    type: redis

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Application-specific settings
sales-point:
  transaction-timeout: 60
  batch-size: 100

otel:
  exporter:
    otlp:
      endpoint: http://jaeger:4318
      protocol: http/protobuf
      retry:
        enabled: true
        max-attempts: 3
        initial-backoff: 1000
        max-backoff: 5000
  logs:
    exporter: none
  metrics:
    exporter: none

# Management endpoints
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,refresh,metrics
  endpoint:
    health:
      show-details: when_authorized